name    'burdara-kegbot'
version '0.1.0'
source 'https://github.com/burdara/puppet-kegbot'
author 'burdara'
license 'Apache License, Version 2.0'
summary 'Module for automating Kegbot server download and installation'
description 'Module for automating Kegbot server download and installation'
project_page 'https://github.com/burdara/puppet-kegbot'
